CC:=g++

sourcedir:=source
headerdir:=header
objectdir:=object
dependdir:=depend
binarydir:=binary
librarydir:=library
docdir:=documentation
exportdir:=export

debugdir:=debug
releasedir:=release
defaultdir:=
coverdir:=cover

sourceextension:=.cc
libraries:=
includedirs:=$(headerdir) catch/include $(librarydir)

# -s flag strips symbols
# not doing this allows a 'client' to run a `gdb main` `bt`
#   which could be useful
defaultflags:=-Wall -Wextra -pedantic -std=c++17
releaseflags:=$(defaultflags) -O2 -s
debugflags:=$(defaultflags) -DDEBUG -ggdb3
coverflags:=$(debugflags) --coverage

name:=main

builds:=default debug release cover

all:debug release

docs:$(docdir)/html/index.html

$(docdir)/html/index.html:header/*.hh source/*.cc
	doxygen doxygen.doxyfile

# optional.  used for library export
#export: release
#	mkdir $(exportdir)
#	ar -cvq $(exportdir)/libArgParse.a $(objectdir)/$(releasedir)/<libname>.o

#TODO:investigate using -fbranch-probabilities
#website appears to be a useful resource:
#  alex.dzyoba.com/linux/profiling-gprof-gcov.html
#  gcovr.com/guide.html

